### ISSUE TITLE
Identify detectors and route to use for map

### ISSUE THREAD

**Issue by ahhdioguy** [Dkreitzer/Team_streprogen_Project1#13]

**Comment by xanendorf** [comment]
We can scale up to a full map when we get it working.
Some ideas-
Thickness/Color of Road depending on Flow/Speed
Animated Car Graphic ala http://planefinder.net/route/SFO/
Snapshot Analysis (Just do one 30s timeframe, we can animate it later)

**Comment by xanendorf** [comment]
We are going to:
declare route to examine
read stat_config into DF
iloc declared route to pull stations
plot stations to gmap
use iloc to pull station data from detector_data.csv
Plot lines to gmap based off of density and speed

**Comment by xanendorf** [comment]
Ive output a list of dataframes for the route. Maybe A nested Dataframe would be a better fit. Im sure I chopped up the Dataframe in a weird way too.
