### ISSUE TITLE
Prevent Duplicate Entries

### ISSUE THREAD

**Issue by xanendorf** [Dkreitzer/Team_streprogen_Project1#18]
I would start at the Data Validation Function

**Comment by yongjinjiang** [comment]
I added a function at the end of TwinCitiesTraffic.ipynb which may solve this time format conversion problem:  
def time_xml2dt(time_xml):
    from time import mktime
    import time
    from datetime import datetime
    #time_xml='Wed Oct 03 10:13:27 CDT 2018'
    B=time_xml.split()
    B.pop(4)
    B[4]=B[4][2:]
    B_struct=time.strptime(' '.join(B), "%a %b %d  %H:%M:%S %y")
    time_dt=datetime.fromtimestamp(mktime(B_struct))
    return time_dt
time_xml='Wed Oct 03 10:13:27 CDT 2018'
time_xml2dt(time_xml)

**Comment by yongjinjiang** [comment]
I added a read_reorder_clean_incidence.ipynb file. Hopefully now we have more ordered incident data. I am not sure what criteria should we use to delete duplicate data..
